// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvbjbxsaudeixhltslu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydmJqYnhzYXVkZWl4aGx0c2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODAwNjUsImV4cCI6MjA2MzU1NjA2NX0.NlbedsqezUVocOMxxYa61cGzqjSSR7p5tTk6TJ6gfpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);