// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhhmcepwfkdrubpuljhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaG1jZXB3ZmtkcnVicHVsamh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzQ5MDcsImV4cCI6MjA2NDQ1MDkwN30.SQ2NSIux2Tls8aLXJdFhmFz-zt287ozFk12ckYnTN-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);